sudo: false
cache: apt
language: cpp

matrix:
  include:
    - env: COMPILER=g++-5
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libboost-dev
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - export CXX=$COMPILER
  - which $CXX

script:
  - rm -rf build;
  - CXX=$COMPILER ./waf distclean configure build --alltests -j1
  - CXX=$COMPILER ./waf distclean configure build_release --alltests -j1
