sudo: false
cache: apt
language: cpp

matrix:
  include:
    - env: COMPILER=g++-4.7
      addons: &gcc47
        apt:
          packages:
            - g++-4.7
            - libboost-dev
            - python-virtualenv
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-4.9
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
            - libboost-dev
            - python-virtualenv
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-5
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libboost-dev
            - python-virtualenv
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - export CXX=$COMPILER
  - which $CXX
  - virtualenv bnf
  - source bnf/bin/activate
  - deactivate

script:
  - rm -rf build;
  - source bnf/bin/activate
  - CXX=$COMPILER ./waf distclean configure build --alltests -j1
  - CXX=$COMPILER ./waf distclean configure build_release --alltests -j1
  - deactivate
